on:
  push:
    repository_dispatch:
      types: [deploy]
    workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: gh api /repos/reborn-soft/prime-t-server/dispatches -f event_type='deploy'
        env:
          GH_TOKEN: ${{ secrets.PAT }}
